# /etc/rsyslog.d/spiedr.conf

input(
    type="imfile"
    File="/opt/spiEDR/logs/spiedr.log"
    Tag="spiEDR"
    Facility="local6"
    Severity="info"
    PersistStateInterval="100"
)

if $programname == "spiEDR" then {
    action(
        type="omfwd"
        Target="<SYSLOG_HOST>"
        Port="514"
        Protocol="tcp"
        TCP_Framing="octet-counted"
        KeepAlive="on"
        Action.ResumeRetryCount="-1"
    )
    stop
}
